import os
from dotenv import load_dotenv
from openai import OpenAI
import json
from data_manage import DataManager
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings
from langchain_core.documents import Document

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PATH = os.path.join(BASE_DIR, "config", ".env")

load_dotenv(PATH)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY").strip().replace("'", "").replace('"', "")
client = OpenAI(api_key=OPENAI_API_KEY)

data_manager = DataManager()


def ai_request(system_prompt: str, user_prompt: str) -> str:
    """
    Sends a request to the OpenAI API using the gpt-4o-mini model.

    Args:
        system_prompt (str): Instructions defining the behavior and role of the AI.
        user_prompt (str): The actual input data or question for the AI to process.

    Returns:
        str: The raw text response generated by the AI model.
    """
    response = client.responses.create(
        model="gpt-4o-mini",
        input=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ],
        max_output_tokens=300,
        temperature=0.5
    )
    print(f"OpenAI response: {response.text}: ")
    return response.output_text


def get_ai_summary(title: str, author: str, description: str) -> str | None:
    """
    Generates a summary for a specific book.
    The summary highlights the main idea, key themes, and target audience
    in a maximum of 3-4 sentences without any markdown formatting.

    Args:
        title (str): The title of the book.
        author (str): The author of the book.
        description (str): Initial description of the book to base the summary on.

    Returns:
        str | None: A clean text summary if successful, or None if an error occurs.
    """
    system_prompt = """
        You are a a personal reading assistant inside a books application, 
        Your goal is to get a summary about books simply and clearly.
        """

    user_prompt = """
        Write a short summary for the book {title} by {author} based on the {description}
        Highlight the main idea, key themes, and explain who would benefit from reading this book.
        Make the response structured, clear, not complicated, in max 3-4 sentences.
        If you don't have the information about the book, please do not suggest, just base on {description}
        Do not use markdown formatting like '**' or '#', write as plain text with paragraphs.
        """

    final_user_prompt = user_prompt.format(title=title, author=author, description=description)

    try:
        response = ai_request(system_prompt, final_user_prompt)
        return response.strip()

    except Exception as e:
        print(f"OpenAI Error in get_ai_summary: {e}")
        return None


def user_preferences(books: list) -> dict | None:
    """
    Analyzes a user's reading history to infer their literary preferences.
    Extracts titles, ratings, and personal user notes from the provided book objects,
    sends them to the AI, and parses the response into a structured dictionary.

    Args:
        books (list): A list of book objects (SQLAlchemy models) belonging to the user.
        Each object should optionally have 'title', 'rating', and 'note' attributes.

    Returns:
        dict | None: A dictionary containing 'genres' (list), 'tones' (list), and
        'summary' (str) if successful. Returns None if the analysis or JSON parsing fails.
    """
    system_prompt = """
        You are a personal reading preference analyst inside a book application.
        Your task is to analyze a user's reading history and infer their literary preferences.
        
        Based only on the provided books, identify:
        - favorite genres
        - preferred tones and writing styles
        - a concise summary of the user's reading taste
        
        Your response must be valid JSON only. Do not include markdown or text outside the JSON.
        """
    books_input = []
    for b in books:
        books_input.append({
            "title": getattr(b, 'title', ''),
            "rating": getattr(b, 'rating', 'None'),
            "note": getattr(b, 'note', '')
        })

    user_prompt = f"""
        Based on these books: {json.dumps(books_input, ensure_ascii=False)}, generate a JSON object:
        {{
            "genres": [],
            "tones": [],
            "summary": ""
        }}
        Return valid JSON only.
        """

    try:
        response = ai_request(system_prompt, user_prompt)
        cleaned_response = response.strip().strip("`").replace("json\n", "", 1)
        return json.loads(cleaned_response)

    except Exception as e:
        print(f"OpenAI Error: {e}")
        return None

def update_user_vectorstore(user_id: int) -> bool:
    """
    Creates or updates a FAISS vector store for a specific user based on their book notes.
    The resulting vector store is saved under a user-specific directory.

    Args:
        user_id (int): The unique identifier of the user whose vector store
                       should be created or updated.

    Returns:
        bool: True if the vector store was successfully created and saved,
              False if no documents (notes) were found for the user.
    """
    user_books = data_manager.get_books_by_user(user_id)

    documents = []
    for book in user_books:
        if book.note:
            content_parts = [
                f"Book: {book.reading_book.title}",
                f"Author: {book.reading_book.author_of_book.author_name}",
                f"My note about this book: {book.note}"
            ]

            if hasattr(book.reading_book, 'description') and book.reading_book.description:
                content_parts.append(f"Description of this book: {book.reading_book.description}")

            full_content = "\n".join(content_parts)

            doc = Document(
                page_content=full_content,
                metadata={
                    "book_id": book.book_id,
                    "title": book.reading_book.title
                }
            )
            documents.append(doc)

    if not documents:
        print(f"User {user_id} has books, but no notes found.")
        return False

    embeddings = OpenAIEmbeddings(api_key=OPENAI_API_KEY, model="text-embedding-3-small")
    vectorstore = FAISS.from_documents(documents, embeddings)

    user_db_path = os.path.join(BASE_DIR, "vector_dbs", f"user_{user_id}")

    vectorstore.save_local(user_db_path)
    print(f"DB for {user_id} created successfully at {user_db_path}")
    return True